name: BloggingWebsite 
title: Blogging-Website 
email: ms4110415@gmail.com
address: sangrur, punjab
phone: '8699594438'
tagline: BlogTheme - Smartest and quickly creating bloging site.
description:  Create Beatifull Blog Site By Importing Our Theme.
baseurl: ''
permalink: /blog/:title
author_name: Manpreet singh
designer: Ram chand
url: https://example.com
copyright_text: © 2020 Blog Theme 
facebook_username: https://www.facebook.com/
twitter_username: https://twitter.com/
instagram_username: https://www.instagram.com/front_end_world/
favicon: /assets/images/avatar.png
paginate: '3'
paginate_path: '/blog/page:num/'
keyboard: "Blogpost,Blogger"
disqus:
  shortname: thefrontendworld 
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
google_analytics: 'G-Your Id'
google_site_verification: 'Your_SITe_Verification_Id'
hero: product_fixed_image
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
getform_id:
mailchimp:
  user-id:
  list-id:
copyright_text: © 2020 Website-Name — Made with  for the people of the internet.
company_url: https://math-world.com
twitter:
  username:
facebook:
  username:
  app_id:
  publisher:
